spring.application.name=notification-service

server.port = 9040
server.servlet.context-path=/notifications

spring.datasource.url=${db_url}
spring.datasource.username=${db_username}
spring.datasource.password=${db_password}
spring.jpa.hibernate.ddl-auto=update

eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true
eureka.server.lease-removal-interval-in-seconds=10
eureka.instance.lease-expiration-duration-in-seconds=10